global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "sample-app"
    static_configs:
      - targets: ["sample-app:8000"]

  - job_name: "jenkins"
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["jenkins:8080"]

